### ISSUE TITLE
anki

### ISSUE THREAD

**Issue by Belle20008** [Belle20008/Bellle#1]
错误
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。
调试信息：
Anki 2.1.45 (e7189f4a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-26 10:38:09
相关扩展:⁨Word Query⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/belle/Library/Application Support/Anki2/addons21/775418273/prepare.py", line 45, in callback
    return func(obj)
  File "/Users/belle/Library/Application Support/Anki2/addons21/775418273/query.py", line 104, in query_from_editor_all_fields
    update_note_fields(editor.note, results)
  File "/Users/belle/Library/Application Support/Anki2/addons21/775418273/query.py", line 141, in update_note_fields
    update_note_field(note, i, q)
  File "/Users/belle/Library/Application Support/Anki2/addons21/775418273/query.py", line 153, in update_note_field
    note.flush()
  File "anki/notes.py", line 81, in flush
AssertionError

**Comment by Belle20008** [comment]
怎么解决呀，看不懂这个
